name: AI Code Analysis

on: [push, pull_request]

jobs:
  analyze-code:
    runs-on: ubuntu-latest
    name: Analyze Project Structure
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3
      
    - name: 🔍 Advanced Code Analysis
      id: analysis
      run: |
        echo "🤖 DÉMARRAGE ANALYSE IA AVANCÉE"
        echo "Dépôt: $GITHUB_REPOSITORY"
        echo "Commit: $GITHUB_SHA"
        echo "Branche: $GITHUB_REF"
        echo ""
        
        # Initialiser les variables pour le rapport
        HTML_STATUS=""
        JS_STATUS=""
        CSS_STATUS=""
        ERRORS_FOUND=0
        WARNINGS=0
        ANALYSIS_REPORT=""
        
        echo "=== STRUCTURE DU PROJET ==="
        PROJECT_STRUCTURE=$(ls -la)
        echo "$PROJECT_STRUCTURE"
        
        echo ""
        echo "=== ANALYSE DÉTAILLÉE DES FICHIERS ==="
        
        # Analyse des fichiers HTML
        echo "🌐 ANALYSE HTML:"
        HTML_REPORT=""
        if [ -f "index.html" ]; then
          LINES=$(wc -l < index.html)
          SIZE=$(wc -c < index.html)
          if [ $LINES -lt 10 ]; then
            HTML_REPORT="$HTML_REPORT❌ index.html: TROP COURT ($LINES lignes)\n"
            ((ERRORS_FOUND++))
          else
            HTML_REPORT="$HTML_REPORT✅ index.html: $LINES lignes, ${SIZE} octets\n"
          fi
        else
          HTML_REPORT="$HTML_REPORT❌ index.html: MANQUANT\n"
          ((ERRORS_FOUND++))
        fi
        
        if [ -f "about.html" ]; then
          LINES=$(wc -l < about.html)
          SIZE=$(wc -c < about.html)
          HTML_REPORT="$HTML_REPORT✅ about.html: $LINES lignes, ${SIZE} octets\n"
        else
          HTML_REPORT="$HTML_REPORT⚠️ about.html: NON TROUVÉ\n"
          ((WARNINGS++))
        fi
        
        # Analyse des fichiers JavaScript
        echo ""
        echo "⚡ ANALYSE JAVASCRIPT:"
        JS_REPORT=""
        JS_FILES=("logic.js" "buttons.js" "history.js")
        for JS_FILE in "${JS_FILES[@]}"; do
          if [ -f "$JS_FILE" ]; then
            LINES=$(wc -l < "$JS_FILE")
            SIZE=$(wc -c < "$JS_FILE")
            if [ $LINES -eq 0 ]; then
              JS_REPORT="$JS_REPORT❌ $JS_FILE: FICHIER VIDE\n"
              ((ERRORS_FOUND++))
            elif [ $LINES -lt 5 ]; then
              JS_REPORT="$JS_REPORT⚠️ $JS_FILE: TRÈS COURT ($LINES lignes)\n"
              ((WARNINGS++))
            else
              JS_REPORT="$JS_REPORT✅ $JS_FILE: $LINES lignes, ${SIZE} octets\n"
            fi
          else
            JS_REPORT="$JS_REPORT❌ $JS_FILE: MANQUANT\n"
            ((ERRORS_FOUND++))
          fi
        done
        
        # Analyse des fichiers CSS
        echo ""
        echo "🎨 ANALYSE CSS:"
        CSS_REPORT=""
        CSS_FILES=("style.css" "theme.css")
        for CSS_FILE in "${CSS_FILES[@]}"; do
          if [ -f "$CSS_FILE" ]; then
            LINES=$(wc -l < "$CSS_FILE")
            SIZE=$(wc -c < "$CSS_FILE")
            if [ $LINES -eq 0 ]; then
              CSS_REPORT="$CSS_REPORT❌ $CSS_FILE: FICHIER VIDE\n"
              ((ERRORS_FOUND++))
            else
              CSS_REPORT="$CSS_REPORT✅ $CSS_FILE: $LINES lignes, ${SIZE} octets\n"
            fi
          else
            CSS_REPORT="$CSS_REPORT⚠️ $CSS_FILE: NON TROUVÉ\n"
            ((WARNINGS++))
          fi
        done
        
        # Vérification des dépendances
        echo ""
        echo "📦 ANALYSE DES DÉPENDANCES:"
        DEPS_REPORT=""
        if [ -f "package.json" ]; then
          DEPS_REPORT="$DEPS_REPORT✅ package.json: PRÉSENT\n"
          if [ -f "package-lock.json" ]; then
            DEPS_REPORT="$DEPS_REPORT✅ package-lock.json: PRÉSENT\n"
          else
            DEPS_REPORT="$DEPS_REPORT⚠️ package-lock.json: MANQUANT\n"
            ((WARNINGS++))
          fi
        else
          DEPS_REPORT="$DEPS_REPORT❌ package.json: MANQUANT\n"
          ((ERRORS_FOUND++))
        fi
        
        # Génération du rapport final
        ANALYSIS_REPORT="=== RAPPORT D'ANALYSE COMPLET ===\n\n"
        ANALYSIS_REPORT+="📊 STATISTIQUES:\n"
        ANALYSIS_REPORT+="• Erreurs critiques: $ERRORS_FOUND\n"
        ANALYSIS_REPORT+="• Avertissements: $WARNINGS\n"
        
        if [ $ERRORS_FOUND -eq 0 ]; then
          ANALYSIS_REPORT+="• Statut: ✅ SUCCÈS\n\n"
        else
          ANALYSIS_REPORT+="• Statut: ❌ ÉCHEC\n\n"
        fi
        
        ANALYSIS_REPORT+="🌐 RAPPORT HTML:\n$HTML_REPORT\n"
        ANALYSIS_REPORT+="⚡ RAPPORT JAVASCRIPT:\n$JS_REPORT\n"
        ANALYSIS_REPORT+="🎨 RAPPORT CSS:\n$CSS_REPORT\n"
        ANALYSIS_REPORT+="📦 RAPPORT DÉPENDANCES:\n$DEPS_REPORT\n"
        
        ANALYSIS_REPORT+="=== ANALYSE TERMINÉE ===\n"
        
        # Sauvegarder le rapport pour l'étape suivante
        echo "ANALYSIS_REPORT<<EOF" >> $GITHUB_OUTPUT
        echo -e "$ANALYSIS_REPORT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
        echo "ERRORS_FOUND=$ERRORS_FOUND" >> $GITHUB_OUTPUT
        echo "WARNINGS=$WARNINGS" >> $GITHUB_OUTPUT
        
        # Afficher le rapport dans les logs
        echo -e "$ANALYSIS_REPORT"

  send-report:
    runs-on: ubuntu-latest
    name: Send Analysis Report
    needs: analyze-code
    
    steps:
    - name: 📧 Send Detailed Report
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "📊 Rapport d'Analyse IA - Commit ${{ github.sha }}"
        to: ${{ secrets.NOTIFICATION_EMAIL }}
        from: "GitHub AI Analyzer"
        body: |
          🤖 RAPPORT D'ANALYSE IA - ${{ github.repository }}
          
          📋 INFORMATIONS DU COMMIT:
          • Dépôt: ${{ github.repository }}
          • Commit: ${{ github.sha }}
          • Branche: ${{ github.ref }}
          • Auteur: ${{ github.actor }}
          • Date: ${{ github.event.head_commit.timestamp }}
          • Lien: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          
          ${{ needs.analyze-code.outputs.ANALYSIS_REPORT }}
          
          📈 RÉSUMÉ EXÉCUTIF:
          ${{ needs.analyze-code.outputs.ERRORS_FOUND }} erreur(s) critique(s) détectée(s)
          ${{ needs.analyze-code.outputs.WARNINGS }} avertissement(s)
          
          {% if needs.analyze-code.outputs.ERRORS_FOUND == 0 %}
          ✅ CODE VALIDE - Prêt pour la production
          {% elif needs.analyze-code.outputs.ERRORS_FOUND == 1 %}
          ⚠️ PROBLÈMES MINEURS - Vérification recommandée
          {% else %}
          ❌ PROBLÈMES CRITIQUES - Action requise
          {% endif %}
          
          Consultez les détails complets sur: 
          https://github.com/${{ github.repository }}/actions
          
          Cordialement,
          Votre IA d'Analyse de Code 🤖